[project]
name = "cis3090-a3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "black>=24.10.0",
    "numpy>=2.1.3",
    "pillow>=11.0.0",
    "warp-lang>=1.4.1",
]
